import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowDown, Clock, MapPin, MessageCircle, Phone, Sparkles, UtensilsCrossed, Users, Flame, Leaf } from "lucide-react";
import { Button } from "@/components/button";
import { OpenStatus } from "@/components/open-status";
import { SectionHeading } from "@/components/section";
import { MiniMenuCard } from "@/components/mini-menu-card";
import { menuItems, whatsappFor } from "@/data/menu";
import heroImage from "@/assets/sithara-hero.jpg";
import interiorImage from "@/assets/sithara-interior.jpg";
import biryaniImage from "@/assets/sithara-biryani.jpg";
import seafoodImage from "@/assets/sithara-seafood.jpg";
import dessertsImage from "@/assets/sithara-desserts.jpg";
const desc="Sithara Grand Family Restaurant near By Pass Junction, Piduguralla. Explore our multi cuisine menu, biryanis, starters, curries, desserts and more.";
export const Route=createFileRoute("/")({head:()=>({meta:[{title:"Sithara Grand Family Restaurant | Piduguralla"},{name:"description",content:desc},{property:"og:title",content:"Sithara Grand Family Restaurant | Piduguralla"},{property:"og:description",content:desc},{property:"og:url",content:"/"},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/"}],scripts:[{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":"Restaurant",name:"Sithara Grand Family Restaurant",telephone:"+919121577737",email:"sitaragrandpdrl@gmail.com",servesCuisine:"Multi Cuisine",address:{"@type":"PostalAddress",streetAddress:"Near By Pass Junction",addressLocality:"Piduguralla",postalCode:"522413",addressCountry:"IN"},openingHours:"Mo-Su 12:00-23:30"})}]}),component:Home});
const pick=(name:string)=>{const item=menuItems.find(i=>i.name===name);if(!item) throw new Error(`Menu item missing: ${name}`);return item};
const standards = [{Icon:Flame,title:"Signature Biryani"},{Icon:UtensilsCrossed,title:"Multi Cuisine"},{Icon:Leaf,title:"Freshly Prepared"},{Icon:Users,title:"Family Dining"}];
const signatures=[pick("SITARA GRAND SPL BIRIYANI"),pick("TANDOORI CHICKEN HALF"),pick("PANEER TIKKA"),pick("APOLO FISH")];
const specials=[pick("RAGI MUDDHA NATU KODI PULUSU"),pick("FAMILY PACK CHICKEN DUM BIRIYANI"),pick("FAMILY PACK MUTTON BIRIYANI")];
function Home(){return <>
<section className="hero"><img className="hero-image" src={heroImage} alt="Royal biryani served in a bronze handi" width={1920} height={1088}/><div className="hero-scrim"/><div className="site-container hero-content"><div className="hero-copy"><p className="hero-kicker"><Sparkles/>SITHARA GRAND</p><h1>WHERE EVERY MEAL<br/>BECOMES A <em>GRAND EXPERIENCE</em></h1><p className="hero-sub">Premium Multi Cuisine Family Restaurant</p><div className="hero-actions"><Button asChild><Link to="/menu" search={{}}>Explore our menu</Link></Button><Button variant="outline" asChild><a href={whatsappFor()} target="_blank" rel="noreferrer"><MessageCircle/>WhatsApp us</a></Button><Button variant="ghost" asChild><a href="tel:+919121577737"><Phone/>Call now</a></Button></div></div><aside className="hero-info"><OpenStatus/><div><Clock/><span><small>Every day</small>12:00 PM – 11:30 PM</span></div><div><MapPin/><span><small>Find us</small>Near By Pass Junction, Piduguralla</span></div></aside></div><a href="#signatures" className="scroll-cue" aria-label="Scroll to signature dishes"><span>SCROLL</span><ArrowDown/></a></section>
<section className="standards"><div className="site-container"><SectionHeading eyebrow="The Sithara standard" title={<>A grand experience, <em>thoughtfully served.</em></>} align="center"/><div className="standards-grid">{standards.map(({Icon,title})=><div className="standard-item" key={title}><Icon/><h3>{title}</h3></div>)}</div></div></section>
<section id="signatures" className="section-dark"><div className="site-container"><SectionHeading eyebrow="Curated favourites" title={<>Our <em>Signatures</em></>} copy="A selection from the official Sithara Grand menu, presented with warmth and character."/><div className="dish-grid">{signatures.map(item=><MiniMenuCard key={item.id} item={item}/>)}</div><div className="mt-10 text-center"><Button asChild><Link to="/menu" search={{}}>Explore full menu</Link></Button></div></div></section>
<section className="section-warm"><div className="site-container"><SectionHeading eyebrow="Made for memorable tables" title={<>Grand <em>Specials</em></>} align="center"/><div className="special-grid">{specials.map(item=><MiniMenuCard key={item.id} item={item} featured/>)}</div></div></section>
<section className="biryani-experience"><img src={biryaniImage} alt="Pot biryani in cinematic warm light" loading="lazy" width={1408} height={1008}/><div className="biryani-overlay"/><div className="site-container biryani-copy"><span className="eyebrow">A celebration in every grain</span><h2>THE SITHARA GRAND<br/><em>BIRYANI EXPERIENCE</em></h2><p>Explore vegetable, chicken, mutton, seafood and pot biryanis exactly as listed on our menu.</p><Button asChild><Link to="/menu" search={{category:"NON - VEG BIRIYANIS"}}>Discover biryanis</Link></Button></div></section>
<section className="story"><div className="site-container story-grid"><div className="story-image"><img src={interiorImage} alt="Warm premium family restaurant dining room" loading="lazy" width={1408} height={1008}/><span>WARM<br/>HOSPITALITY</span></div><div><SectionHeading eyebrow="Our story" title={<>Made for families.<br/><em>Remembered for flavour.</em></>} copy="Sithara Grand brings multi-cuisine dining, generous choices and warm hospitality together under one roof in Piduguralla."/><p className="body-copy">From relaxed family lunches to unhurried evening meals, every visit is designed around good food, attentive service and time shared at the table.</p><Button variant="outline" asChild><Link to="/about">Our restaurant</Link></Button></div></div></section>
<section className="gallery-band"><div className="site-container"><SectionHeading eyebrow="A glimpse inside" title={<>Food, mood & <em>moments</em></>} align="center"/><div className="gallery-grid"><img src={interiorImage} alt="Sithara dining atmosphere" loading="lazy"/><img src={seafoodImage} alt="Fish and prawns restaurant presentation" loading="lazy"/><img src={dessertsImage} alt="Desserts and refreshing drinks" loading="lazy"/><img src={biryaniImage} alt="Sithara biryani experience" loading="lazy"/></div></div></section>
<section className="visit-band"><div className="site-container visit-grid"><div><span className="eyebrow">Find us</span><h2>COME VISIT<br/><em>SITHARA GRAND</em></h2><p>Sithara Grand Family Restaurant<br/>Near By Pass Junction<br/>Piduguralla - 522413</p></div><div className="visit-actions"><OpenStatus/><Button asChild><a href="https://www.google.com/maps/search/?api=1&query=Sithara%20Grand%20Family%20Restaurant%2C%20Near%20By%20Pass%20Junction%2C%20Piduguralla%20-%20522413" target="_blank" rel="noreferrer"><MapPin/>Get directions</a></Button><Button variant="outline" asChild><Link to="/contact">Contact us</Link></Button></div></div></section>
</>}
